# Домашнее задание: Pandas и Titanic

---

# Homework: Pandas and Titanic

## Загрузка данных / Loading Data

Выполните ячейку ниже для загрузки датасета.

In [250]:
import pandas as pd

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Описание столбцов / Column Descriptions

| Столбец / Column | Описание / Description |
|------------------|------------------------|
| PassengerId | Идентификатор пассажира / Passenger ID |
| Survived | Выжил (1) или нет (0) / Survived (1) or not (0) |
| Pclass | Класс билета (1, 2 или 3) / Ticket class (1, 2, or 3) |
| Name | Имя пассажира / Passenger name |
| Sex | Пол (male/female) / Gender (male/female) |
| Age | Возраст / Age |
| SibSp | Кол-во братьев/сестёр/супругов на борту / Number of siblings/spouses aboard |
| Parch | Кол-во родителей/детей на борту / Number of parents/children aboard |
| Ticket | Номер билета / Ticket number |
| Fare | Стоимость билета / Ticket fare |
| Cabin | Номер каюты / Cabin number |
| Embarked | Порт посадки / Port of embarkation (C=Cherbourg, Q=Queenstown, S=Southampton) |

### Задача 1
Сколько строк и столбцов в датасете? Сколько пассажиров выжило, а сколько погибло?

In [251]:
print(f"В датасете (строк, столбцов): {df.shape}")
print(f"Пассжиров выжило {sum(df['Survived'] == 1 )}")
print(f"Пассжиров погибло {sum(df['Survived'] == 0 )}")

В датасете (строк, столбцов): (891, 12)
Пассжиров выжило 342
Пассжиров погибло 549

### Задача 2
Выведите пассажиров, которые:
- Женщины ИЛИ дети (возраст < 16)
- И при этом НЕ выжили

Сколько таких пассажиров?

In [252]:
df1 = df.query('Sex == "female" or Age < 16')
print(df1.sample(3))
print(f"Всего: {len(df1)}\n")

df2 = df.query('(Sex == "female" or Age < 16) and Survived == 0')
print(df2.sample(3))
print(f"Всего: {len(df2)}\n")

     PassengerId  Survived  Pclass                             Name     Sex  \
816          817         0       3     Heininen, Miss. Wendla Maria  female
32            33         1       3         Glynn, Miss. Mary Agatha  female
803          804         1       3  Thomas, Master. Assad Alexander    male

       Age  SibSp  Parch            Ticket    Fare Cabin Embarked
816  23.00      0      0  STON/O2. 3101290  7.9250   NaN        S
32     NaN      0      0            335677  7.7500   NaN        Q
803   0.42      0      1              2625  8.5167   NaN        C
Всего: 354

     PassengerId  Survived  Pclass                                    Name  \
863          864         0       3       Sage, Miss. Dorothy Edith "Dolly"
199          200         0       2  Yrois, Miss. Henriette ("Mrs Harbeck")
235          236         0       3            Harknett, Miss. Alice Phoebe

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
863  female   NaN      8      2    CA. 2343  69.55   NaN        S
199  female  24.0      0      0      248747  13.00   NaN        S
235  female   NaN      0      0  W./C. 6609   7.55   NaN        S
Всего: 100

### Задача 3
Найдите медианную стоимость билета (Fare) для каждого класса (Pclass). В каком классе самый большой разброс цен (максимальная - минимальная)?

In [253]:
df1 = (df.query("Pclass == 1"))
print(f"Медианная стоимость билета для класса {df1["Pclass"].mean()} составляет {df1["Fare"].mean():.2f}")

df2 = (df.query("Pclass == 2"))
print(f"Медианная стоимость билета для класса {df2["Pclass"].mean()} составляет {df2["Fare"].mean():.2f}")

df3 = (df.query("Pclass == 3"))
print(f"Медианная стоимость билета для класса {df3["Pclass"].mean()} составляет {df3["Fare"].mean():.2f}")

Медианная стоимость билета для класса 1.0 составляет 84.15
Медианная стоимость билета для класса 2.0 составляет 20.66
Медианная стоимость билета для класса 3.0 составляет 13.68

### Задача 4
Для каждой комбинации класса (Pclass) и порта посадки (Embarked) посчитайте:
- Количество пассажиров
- Процент выживших
- Средний возраст

In [254]:
groupby_data = df.groupby(['Pclass', 'Embarked']).aggregate({
    'Survived': ['sum','count'],
    'Age': 'mean'
}).round(1)
# print(groupby_data)

result_df = pd.DataFrame()
result_df['Passenger'] = groupby_data[('Survived','count')]
result_df['Survival_percent'] = (100*groupby_data[('Survived','sum')]/groupby_data[('Survived','count')]).round(1)
result_df['Mean_age'] = groupby_data[('Age','mean')]

print(result_df)

                 Passenger  Survival_percent  Mean_age
Pclass Embarked
1      C                85              69.4      38.0
       Q                 2              50.0      38.5
       S               127              58.3      38.2
2      C                17              52.9      22.8
       Q                 3              66.7      43.5
       S               164              46.3      30.4
3      C                66              37.9      20.7
       Q                72              37.5      25.9
       S               353              19.0      25.7

### Задача 5
Извлеките титул (Mr, Mrs, Miss, Master, Dr и т.д.) из имени каждого пассажира в новый столбец `Title`.

Формат имени: `"Фамилия, Титул. Имя"`  
Например: `"Braund, Mr. Owen Harris"` → `"Mr"`

Выведите количество пассажиров с каждым титулом.

*Подсказка: используйте .str.split() или .str.extract()*

In [255]:
df['Title'] = df['Name'].apply(lambda x: x.split('.')[0].split()[-1])
print(df['Title'].value_counts())

Title
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Col           2
Mlle          2
Major         2
Ms            1
Mme           1
Don           1
Lady          1
Sir           1
Capt          1
Countess      1
Jonkheer      1
Name: count, dtype: int64

### Задача 6
Создайте столбец `FamilySize = SibSp + Parch + 1` (размер семьи включая самого пассажира).

Найдите, при каком размере семьи выживаемость максимальная, а при каком — минимальная.

In [318]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

groupby_data = df.groupby(['FamilySize']).agg(
    Survived_sum=('Survived', 'sum'),
    Passenger_count=('Survived', 'count'))
groupby_data['Survival_percent'] = (100*groupby_data['Survived_sum']/groupby_data['Passenger_count']).round(1)

print(groupby_data,'\n')

print(f"Максимальная выживаемость при размере семьи: {groupby_data['Survival_percent'].idxmax()}")
print(f"Минимальная выживаемость при размере семьи: {groupby_data['Survival_percent'].idxmin()}")

            Survived_sum  Passenger_count  Survival_percent
FamilySize
1                    163              537              30.4
2                     89              161              55.3
3                     59              102              57.8
4                     21               29              72.4
5                      3               15              20.0
6                      3               22              13.6
7                      4               12              33.3
8                      0                6               0.0
11                     0                7               0.0

Максимальная выживаемость при размере семьи: 4
Минимальная выживаемость при размере семьи: 8

### Задача 7
В столбце Age много пропусков. Заполните их **медианным возрастом** для соответствующей группы по полу (Sex) и классу (Pclass).

Например: пропуск у женщины из 1-го класса заполняется медианным возрастом женщин 1-го класса.

Сохраните результат в новый столбец `AgeFilled`.

In [257]:
df['AgeMeanByGroup'] = df.groupby(['Sex', 'Pclass'])['Age'].transform('mean')
df['AgeFilled'] = df['Age'].fillna(df['AgeMeanByGroup'])
df = df.drop('AgeMeanByGroup', axis=1)

print(f"Пропуски до: {df['Age'].isnull().sum()}")
print(f"Пропуски после: {df['AgeFilled'].isnull().sum()}")

df.tail(3)

Пропуски до: 177
Пропуски после: 0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,FamilySize,AgeFilled
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S,Miss,4,21.75
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C,Mr,1,26.00
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q,Mr,1,32.00

### Задача 8
Создайте столбец `AgeGroup` с категориями:
- `'Child'`: возраст < 12
- `'Teen'`: 12 ≤ возраст < 18
- `'Adult'`: 18 ≤ возраст < 60
- `'Senior'`: возраст ≥ 60

Постройте сводную таблицу (pivot table): **процент выживших** для каждой комбинации возрастной группы и пола.

In [258]:
categorize = lambda age: next(c for a, c in [(12, 'Child'), (18, 'Teen'), (60, 'Adult'), (float('inf'), 'Senior')] if age < a)
df['AgeGroup'] = df['AgeFilled'].apply(categorize)


groupby_data = df.groupby(['Sex', 'AgeGroup']).aggregate({
    'Survived': ['sum','count'],
})
groupby_data['Survival_percent'] = (100*groupby_data[('Survived','sum')]/groupby_data[('Survived','count')]).round(1)
groupby_data

                Survived       Survival_percent
                     sum count
Sex    AgeGroup
female Adult         191   255             74.9
       Child          19    32             59.4
       Senior          4     4            100.0
       Teen           19    23             82.6
male   Adult          83   497             16.7
       Child          20    36             55.6
       Senior          3    22             13.6
       Teen            3    22             13.6

### Задача 9
Извлеките букву палубы из номера каюты (Cabin) — это первый символ (например, `"C85"` → `"C"`).

Для пассажиров с известной каютой:
1. Найдите процент выживших на каждой палубе
2. Какая палуба была самой безопасной?
3. Есть ли связь между палубой и классом билета?

In [259]:
df['Deck'] = df['Cabin'].str[0]
groupby_data = df.groupby(['Deck']).aggregate({'Survived': ['sum','count']})
groupby_data['Survival_percent'] = (100*groupby_data[('Survived','sum')]/groupby_data[('Survived','count')]).round(1)

print(groupby_data)
print()
print(f"Самая безопасная палуба: {groupby_data['Survival_percent'].idxmax()}")
print()
print(df.groupby(['Deck','Pclass']).aggregate({'Survived': ['sum','count']}))

     Survived       Survival_percent
          sum count
Deck
A           7    15             46.7
B          35    47             74.5
C          35    59             59.3
D          25    33             75.8
E          24    32             75.0
F           8    13             61.5
G           2     4             50.0
T           0     1              0.0

Самая безопасная палуба: D

            Survived
                 sum count
Deck Pclass
A    1             7    15
B    1            35    47
C    1            35    59
D    1            22    29
     2             3     4
E    1            18    25
     2             3     4
     3             3     3
F    2             7     8
     3             1     5
G    3             2     4
T    1             0     1

### Задача 10
Проверьте гипотезу «Женщины и дети первыми».

Создайте столбец `Priority`:
- `'High'`: женщины или дети (возраст < 16)
- `'Low'`: остальные (мужчины 16+)

Для каждого класса (Pclass) посчитайте:
- Процент выживших с высоким приоритетом
- Процент выживших с низким приоритетом
- Разницу между ними

В каком классе принцип «женщины и дети первыми» соблюдался лучше всего?

In [312]:
df['Priority'] = df.apply(lambda row: 'Low' if (row['Sex']=='male') and (row['AgeFilled'] >=16) else 'High',axis=1)

groupby_data = df.groupby(['Pclass', 'Priority']).agg(
    Survived_sum=('Survived', 'sum'),
    Passenger_count=('Survived', 'count'))
groupby_data['Survival_percent'] = (100*groupby_data['Survived_sum']/groupby_data['Passenger_count']).round(1)

print(f"\nПринцип «женщины и дети первыми» соблюдался лучше всего в классе: {groupby_data.xs('High', level='Priority')['Survival_percent'].idxmax()}\n")

groupby_data['Differents'] = 0.0
for id in groupby_data.index:
    if (id[1]=='High'):
        groupby_data.loc[id,'Differents'] = groupby_data.loc[id,'Survival_percent'] - groupby_data.loc[(id[0],'Low'),'Survival_percent']

print(groupby_data)

Принцип «женщины и дети первыми» соблюдался лучше всего в классе: 1

                 Survived_sum  Passenger_count  Survival_percent  Differents
Pclass Priority
1      High                94               97              96.9        61.6
       Low                 42              119              35.3         0.0
2      High                79               85              92.9        84.8
       Low                  8               99               8.1         0.0
3      High                81              172              47.1        35.2
       Low                 38              319              11.9         0.0